server.port=8080
spring.application.name=generador-bd

# Conexion PostgreSQL hardcode para CRUD en vivo y codigo PHP generado
crud.db.host=localhost
crud.db.port=5432
crud.db.user=postgres
crud.db.password=2219
